### ISSUE TITLE
Make it work for `Outlet Collection`s

### ISSUE THREAD

**Issue by chrisfsampaio** [fpg1503/OptionalOutlets#2]

**Comment by fpg1503** [comment]
Fixed in 9459cf970b17b2c84bd1015ba7a5d780ea11b023.

The `private` regex works since it matches everything until `[`, I'll leave that as is for now (it shouldn't be a problem).

**Comment by chrisfsampaio** [comment]
But the implicitly unwrapped optionals do not turn into optionals AFAIK.

**Comment by fpg1503** [comment]
It was broken but it should be fixed as of 9459cf970b17b2c84bd1015ba7a5d780ea11b023. Have you tried again in the new version? It's working fine here.

**Comment by chrisfsampaio** [comment]
ops, totally missed that. Works now 👍
