### ISSUE TITLE
private not optional

### ISSUE THREAD

**Issue by piv199** [fpg1503/OptionalOutlets#3]
If I want only private and ImplicitlyUnwrapped IBOutlets, what should I do?

**Comment by fpg1503** [comment]
I'm glad you figured it out but just for future reference the solution is:
Toggle `Turn '!' into '?' in @IBOutlets` under the **Editor** menu.
<img width="295" alt="screen shot 2016-09-02 at 12 57 58 pm" src="https://cloud.githubusercontent.com/assets/5491536/18210023/f519e852-710c-11e6-8dd6-f0bc5278b634.png">
